#!/bin/bash
tmp=fsflgdgmdslgndlgndfgldfmgddfdfgf.fdsf


for f in $@; do
	[[ ! -f $f ]] && continue
	ptitle=$( sed -n '/<title>/ s,^[^>]*>\([^<]*\)<.*$,\1,p' "$f")
	# clear header/footer
	sed -i '1,/title_main/ { /title_main/!d }' "$f"
	sed -i '/id="footer/,$ d' "$f"

	# add front matter
	{
		echo ---
		echo -n 'title: "'
		title=$(sed -n '1 s,^[^>]*>\([^<]*\)<.*$,\1,p' "$f" | sed 's,^\s*,,; s,\s*$,,')
		[[ -z $ptitle ]] && echo -n $title || echo -n $ptitle
		echo '"'
		echo ---
		cat "$f"
	} > $tmp
	mv $tmp "$f"
done
